### ISSUE TITLE
Bugs or features?

### ISSUE THREAD

**Issue by eyesdrib** [Rotrics-Dev/rotrics-studio-app-issue#2]
Hey @liumingzw I appreciate your work on Studio. These aren't necessarily issues, but I thought I'd bring them up....

If I abort a laser engraving, invariably the laser stops moving and the laser stays on at high power, burning into my surface and I have to be quick to get over to Basic and turn the laser off. It would be helpful if a "stop send" turned it off every time.

The previews for the various dithering algorithms all appear to be the same regardless of my selection. I haven't figured out my optimal setting for a true greyscale etching, so that may be on me.

Thank you again. 

Henry

**Comment by MichaelDu9226** [comment]
Thanks for your advice.
This function has been completed.
I'll close this issue. if there is a problem, please contact me.
